spring:
  profiles:
    active: "local"

---
spring:

  profiles: "local"
  # Data config
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:h2:mem:companydb
    driverClassName: org.h2.Driver
    username: sa
    password: password

# Server Config
server:
  port: 9090
  servlet:
    context-path: "/sample-company"

# Logging
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.lunatech.springworkshop: DEBUG
    org.hibernate: ERROR

---
spring:
  profiles: "dev"
  # Data config
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/company
    username: root
    password: password

# Server Config
server:
  port: 9090
  servlet:
    context-path: "/sample-company"

# Logging
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.lunatech.springworkshop: DEBUG
    org.hibernate: DEBUG
